spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_ null

jwt:
  secret: dfd8fe2a-50b2-464d-ac60-0b6b6090a1db
  expiration: 999999