spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_ null

jwt:
  secret: 3bfdb3e5-16d6-4b0a-998a-e174c24b324b
  expiration: 999999


